### ISSUE TITLE
Undefined configuration content?

### ISSUE THREAD

**Issue by yuqing26** [intelligent-control-lab/guard#1]
Hello! Thanks for releasing the code. In safe_rl_env_config_noconti.py, when the task is for instance "drone1_noconti", there is "ghosts_mode" in the configuration, but in the engine.py, I cannot find the default configuration for this task. Could you please release the config files? Thanks!

**Comment by yuqing26** [comment]
Hello! I find that if I delete the "ghosts_mode" and "ghost3Ds_mode" in the config file safe_rl_env_config_noconti.py, then it can run correctly. And since the ghost_num and ghost3Ds_num in these tasks are all 0, it will not influence the results. Thanks!

**Comment by CaesarAndylaw** [comment]
Hi thanks for your feedback! This is indeed a great question, which is caused by that the SCPO related noconti environment is behind the newest GUARD environment engine, which doesn't support ghosts_mode anymore. We have merged the safe_rl_env_config_noconti.py into safe_rl_env_config.py. Now you can directly use the same testing suite in GUARD and add additional 'noconti' in the rear to create non-continuous environment that is suitable for SCPO related experiments.  For example, you can use 'Push_Swimmer_6Hazards_noconti' to create a Push task using Swimmer robot and 6 Hazards non-continuous environment. Let me know if there's additional issue we can help with.

**Comment by yuqing26** [comment]
It now works! Thank you so much for your quick response!
