### ISSUE TITLE
too many values to unpack (expected 3) in CPO

### ISSUE THREAD

**Issue by xueliu8617112** [intelligent-control-lab/guard#2]
Hello, in cpo.py, line 317, there are some errors when i run the code.
<img width="1326" alt="image" src="https://github.com/intelligent-control-lab/guard/assets/50107489/8bdc9864-7bf6-479e-bd5a-c9d9c4df2e1b">
i think that some like data['act'] should be deleted .

**Comment by Haihan-W** [comment]
I encountered the exact same problem when running cpo.py, but I found that the reason is because the number of variables in the left hand side is 3 but there are more than 3 values at the right hand side. So if you just delete the irrelevant values at the right hand side and only keep the 3 that correspond to left hand side variable, the code should work fine.

**Comment by LiangZhisama** [comment]
Thanks for the correction, and I'm sorry for our oversight in normalizing the files! This issue has now been fixed.

**Comment by CaesarAndylaw** [comment]
The issue is fixed, and no additional concern is raised. The issue is closed.
